import type { LegalSource } from './domain.js';
import { type Language, localized } from './i18n.js';
export type ProjectProfile = { name: string; processesPersonalData?: boolean; usesProviders?: boolean; sellsOnline?: boolean; storesSensitiveData?: boolean };
export function assessProject(project: ProjectProfile, sources: LegalSource[], language: Language = 'es') {
  const risks: string[] = [], controls: string[] = [], questions: string[] = [];
  if (project.processesPersonalData) { risks.push(localized(language, 'El proyecto trata datos personales y requiere identificar base jurídica, transparencia y medidas de seguridad.', 'The project processes personal data and requires a legal basis, transparency, and security measures.')); controls.push(localized(language, 'Inventariar tratamientos, finalidades, responsables, encargados y plazos de conservación.', 'Inventory processing activities, purposes, controllers, processors, and retention periods.')); }
  if (project.storesSensitiveData) { risks.push(localized(language, 'El tratamiento de datos sensibles requiere controles reforzados y revisión especializada.', 'Processing sensitive data requires enhanced controls and specialist review.')); controls.push(localized(language, 'Aplicar minimización, control de acceso, cifrado y evaluación de impacto cuando corresponda.', 'Apply minimization, access control, encryption, and an impact assessment where applicable.')); }
  if (project.usesProviders) { risks.push(localized(language, 'Los proveedores que acceden a datos deben tener responsabilidades y garantías documentadas.', 'Providers accessing data must have documented responsibilities and safeguards.')); controls.push(localized(language, 'Formalizar contratos, instrucciones, subencargados, confidencialidad y gestión de incidentes.', 'Formalize contracts, instructions, subprocessors, confidentiality, and incident management.')); }
  if (project.sellsOnline) { risks.push(localized(language, 'La venta digital requiere revisar información al consumidor, contratación y comprobantes aplicables.', 'Digital sales require reviewing consumer information, contracting, and applicable receipts.')); controls.push(localized(language, 'Documentar términos, privacidad, devoluciones, soporte y evidencia de consentimiento.', 'Document terms, privacy, returns, support, and consent evidence.')); }
  if (!project.processesPersonalData && project.processesPersonalData !== false) questions.push(localized(language, '¿El sistema recolecta, consulta, almacena o comparte datos de personas?', 'Does the system collect, access, store, or share personal data?'));
  if (!project.name?.trim()) throw new Error(localized(language, 'El proyecto requiere un nombre', 'The project requires a name'));
  if (risks.length === 0) questions.push(localized(language, '¿Qué datos, usuarios, proveedores y canales de comercialización intervienen?', 'Which data, users, providers, and sales channels are involved?'));
  const topics = new Set<string>();
  if (project.processesPersonalData || project.storesSensitiveData || project.usesProviders) { topics.add('datos personales'); topics.add('privacidad'); }
  if (project.sellsOnline) { topics.add('comercio electrónico'); topics.add('consumidores'); topics.add('facturación electrónica'); }
  const relevant = sources.filter(source => source.topics.some(topic => topics.has(topic)));
  return { project: project.name, language, risks, controls, questions, references: relevant.map(({ id, title, url, verifiedAt, status }) => ({ id, title, url, verifiedAt, status })), disclaimer: localized(language, 'Orientación preliminar; no constituye dictamen ni certificación jurídica.', 'Preliminary guidance; this is not a legal opinion or certification.') };
}
export function auditChecklist(project: ProjectProfile, sources: LegalSource[], language: Language = 'es') { const a = assessProject(project, sources, language); return { project: a.project, language, items: [...a.controls.map((text) => ({ text, evidence: localized(language, 'Definir evidencia y responsable', 'Define evidence and owner'), status: localized(language, 'pendiente', 'pending') })), { text: localized(language, 'Revisar fuentes y vigencia', 'Review sources and legal status'), evidence: a.references.map((r) => r.url).join(', '), status: localized(language, 'pendiente', 'pending') }], disclaimer: a.disclaimer }; }
