import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { join, resolve } from 'node:path';

export type LifecycleAction = { id: string; area: string; problem: string; priority: string; suggestedOwner: string; steps: string[]; expectedEvidence: string[]; completionCriteria: string; status: 'pendiente' | 'en_progreso' | 'cerrada' | 'aceptada_temporalmente'; owner?: string; dueDate?: string; evidenceIds?: string[]; exceptionIds?: string[] };
export type GovernanceLifecycleState = { schemaVersion: 1; project?: string; audits: Array<{ id: string; generatedAt: string; project?: string; summary: unknown; reportPath: string; sha256: string }>; actions: LifecycleAction[]; exceptions: Array<{ id: string; actionId: string; reason: string; approvedBy: string; expiresAt: string; createdAt: string }>; evidence: Array<{ id: string; actionId: string; description: string; uri: string; addedBy: string; addedAt: string }>; history: Array<{ id: string; at: string; actor: string; type: string; targetId?: string; details: unknown }> };

const emptyState = (): GovernanceLifecycleState => ({ schemaVersion: 1, audits: [], actions: [], exceptions: [], evidence: [], history: [] });

export function createGovernanceLifecycle(root: string) {
  const directory = join(resolve(root), '.mcp-governance');
  const statePath = join(directory, 'lifecycle.json');
  const load = async (): Promise<GovernanceLifecycleState> => { try { return { ...emptyState(), ...JSON.parse(await readFile(statePath, 'utf8')) }; } catch { return emptyState(); } };
  const persist = async (state: GovernanceLifecycleState) => { await mkdir(join(directory, 'audits'), { recursive: true }); await writeFile(statePath, JSON.stringify(state, null, 2) + '\n', 'utf8'); return state; };
  const event = (state: GovernanceLifecycleState, actor: string, type: string, targetId: string | undefined, details: unknown) => state.history.push({ id: `event-${Date.now()}-${state.history.length + 1}`, at: new Date().toISOString(), actor, type, targetId, details });
  return {
    load,
    async evolution() { const state = await load(); const previous = state.audits.at(-2)?.summary as any; const current = state.audits.at(-1)?.summary as any; return { previousScore: previous?.complianceScore ?? null, currentScore: current?.complianceScore ?? null, closedFindings: Math.max(0, (previous?.totalAuditFindings ?? 0) - (current?.totalAuditFindings ?? 0)), newFindings: Math.max(0, (current?.totalAuditFindings ?? 0) - (previous?.totalAuditFindings ?? 0)), overdueRisks: state.actions.filter(action => action.dueDate && action.status !== 'cerrada' && new Date(action.dueDate).getTime() < Date.now()).length, auditsCompared: previous ? 2 : 1 }; },
    async recordAudit(report: any, actor: string) { const state = await load(); const id = `audit-${Date.now()}`; const content = JSON.stringify(report, null, 2); const reportPath = join(directory, 'audits', `${id}.json`); await mkdir(join(directory, 'audits'), { recursive: true }); await writeFile(reportPath, content + '\n', 'utf8'); state.project = report.executiveSummary?.project ?? report.project; state.audits.push({ id, generatedAt: report.generatedAt, project: state.project, summary: report.executiveSummary, reportPath, sha256: createHash('sha256').update(content).digest('hex') }); for (const action of report.remediationPlan ?? []) { const existing = state.actions.find(item => item.id === action.id); if (!existing) state.actions.push({ ...action, status: 'pendiente', evidenceIds: [], exceptionIds: [] }); } event(state, actor, 'audit_recorded', id, { actionCount: report.remediationPlan?.length ?? 0 }); await persist(state); return { auditId: id, state }; },
    async updateAction(id: string, update: Partial<Pick<LifecycleAction, 'status' | 'owner' | 'dueDate'>>, actor: string) { const state = await load(); const action = state.actions.find(item => item.id === id); if (!action) throw new Error(`Acción no encontrada: ${id}`); Object.assign(action, update); event(state, actor, 'action_updated', id, update); return persist(state); },
    async addEvidence(actionId: string, evidence: { description: string; uri: string }, actor: string) { const state = await load(); const action = state.actions.find(item => item.id === actionId); if (!action) throw new Error(`Acción no encontrada: ${actionId}`); if (!evidence.description || !evidence.uri) throw new Error('description y uri son obligatorios para registrar evidencia.'); const item = { id: `evidence-${Date.now()}-${state.evidence.length + 1}`, actionId, ...evidence, addedBy: actor, addedAt: new Date().toISOString() }; state.evidence.push(item); action.evidenceIds = [...(action.evidenceIds ?? []), item.id]; event(state, actor, 'evidence_added', actionId, item); return persist(state); },
    async addException(actionId: string, exception: { reason: string; approvedBy: string; expiresAt: string }, actor: string) { const state = await load(); const action = state.actions.find(item => item.id === actionId); if (!action) throw new Error(`Acción no encontrada: ${actionId}`); if (!exception.reason || !exception.approvedBy || !exception.expiresAt) throw new Error('reason, approvedBy y expiresAt son obligatorios para una excepción.'); const item = { id: `exception-${Date.now()}-${state.exceptions.length + 1}`, actionId, ...exception, createdAt: new Date().toISOString() }; state.exceptions.push(item); action.exceptionIds = [...(action.exceptionIds ?? []), item.id]; action.status = 'aceptada_temporalmente'; event(state, actor, 'exception_approved', actionId, item); return persist(state); },
  };
}
